#!/bin/bash

BUILD_TYPE="RELEASE"

if [ $# -eq 1 ]; then
   if [ $1 = "DEBUG" ]; then
       BUILD_TYPE=DEBUG
   else
       echo "Wrong build type $1, building RELEASE"
   fi
fi

echo "> cd $(dirname "$0")/.."
cd $(dirname "$0")/..

# Install pwng-server

echo "> mkdir -p build"
mkdir -p build
echo "> cd build"
cd build
echo "> cmake .. -DCMAKE_PREFIX_PATH=../install -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=$BUILD_TYPE"
cmake .. -DCMAKE_PREFIX_PATH=../install -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=$BUILD_TYPE
make -j8 install

echo "> cd $(dirname "$0")/.."
cd $(dirname "$0")/..
